import 'package:flutter/material.dart';import 'package:loc_s_application_booking/core/app_export.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_one.dart';import 'package:loc_s_application_booking/widgets/app_bar/custom_app_bar.dart';import 'package:loc_s_application_booking/widgets/custom_elevated_button.dart';import 'package:loc_s_application_booking/widgets/custom_floating_text_field.dart';import 'package:loc_s_application_booking/widgets/custom_outlined_button.dart';
// ignore_for_file: must_be_immutable
class InputInfoScreen extends StatelessWidget {InputInfoScreen({Key? key}) : super(key: key);

TextEditingController fullNameTextFieldController = TextEditingController();

TextEditingController genderTextFieldController = TextEditingController();

TextEditingController dateOfBirthTextFieldController = TextEditingController();

TextEditingController passportValueTextFieldController = TextEditingController();

TextEditingController expirationDateTextFieldController = TextEditingController();

TextEditingController contactFullNameTextFieldController = TextEditingController();

TextEditingController phoneNumberTextFieldController = TextEditingController();

TextEditingController emailTextFieldController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.blue50, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(child: SizedBox(height: 756.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildSearchColumn(context), SizedBox(height: 15.v), _buildInfo(context), SizedBox(height: 15.v), _buildContactInfo(context)]))), _buildTotalPriceFooterRow(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 92.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 10.h, top: 19.v, bottom: 49.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleOne(text: "Nhập thông tin", margin: EdgeInsets.only(left: 10.h, top: 22.v, bottom: 49.v)), styleType: Style.bgGradientnamelightblue500nameprimary); } 
/// Section Widget
Widget _buildSearchColumn(BuildContext context) { return Container(width: 350.h, padding: EdgeInsets.all(15.h), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 46.h), child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Container(width: 64.h, margin: EdgeInsets.only(bottom: 14.v), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 1.v), decoration: AppDecoration.secondary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Text("Chiều đi", style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 10.h), child: _buildFlightDetailsColumn2(context, cityName: "Hà Nội", time: "20:15")), CustomImageView(imagePath: ImageConstant.imgArrowTransferBlack900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 7.h, top: 10.v, bottom: 8.v)), Padding(padding: EdgeInsets.only(left: 6.h), child: _buildFlightDetailsColumn1(context, cityName: "Đà Nẵng", time: "06:50")), Padding(padding: EdgeInsets.only(left: 11.h, top: 3.v), child: _buildFlightDetailsColumn3(context, dateText: "T5, 18 Thg11 ", labelText: "VJ148"))])), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(right: 46.h), child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Container(width: 64.h, margin: EdgeInsets.only(bottom: 14.v), padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 1.v), decoration: AppDecoration.secondary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Text("Chiều về", style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 9.h), child: _buildFlightDetailsColumn1(context, cityName: "Đà Nẵng", time: "20:15")), CustomImageView(imagePath: ImageConstant.imgArrowTransferBlack900, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 10.v, bottom: 8.v)), Padding(padding: EdgeInsets.only(left: 7.h), child: _buildFlightDetailsColumn2(context, cityName: "Hà Nội", time: "06:50")), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: _buildFlightDetailsColumn3(context, dateText: "T5, 18 Thg11 ", labelText: "VJ148"))]))])); } 
/// Section Widget
Widget _buildQuickEntryButton(BuildContext context) { return CustomOutlinedButton(text: "Nhập nhanh danh sách hành khách", rightIcon: Container(margin: EdgeInsets.only(left: 10.h), child: CustomImageView(imagePath: ImageConstant.imgUsermultiplegroupclosegeometrichumanmultiplepersonupuser, height: 22.adaptSize, width: 22.adaptSize)), buttonStyle: CustomButtonStyles.outlineBlueTL6, buttonTextStyle: theme.textTheme.titleSmall!); } 
/// Section Widget
Widget _buildFullNameTextField(BuildContext context) { return CustomFloatingTextField(controller: fullNameTextFieldController, labelText: "Họ và Tên", labelStyle: theme.textTheme.bodyMedium!, hintText: "Họ và Tên"); } 
/// Section Widget
Widget _buildGenderTextField(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 5.h), child: CustomFloatingTextField(controller: genderTextFieldController, labelText: "Giới tính", labelStyle: theme.textTheme.bodyMedium!, hintText: "Giới tính"))); } 
/// Section Widget
Widget _buildDateOfBirthTextField(BuildContext context) { return CustomFloatingTextField(width: 110.h, controller: dateOfBirthTextFieldController, labelText: "Ngày sinh", labelStyle: theme.textTheme.bodyMedium!, hintText: "Ngày sinh", contentPadding: EdgeInsets.only(top: 23.v), borderDecoration: FloatingTextFormFieldStyleHelper.custom, filled: false); } 
/// Section Widget
Widget _buildPassportValueTextField(BuildContext context) { return CustomFloatingTextField(width: 92.h, controller: passportValueTextFieldController, labelText: "Passport", labelStyle: theme.textTheme.bodyMedium!, hintText: "Passport", contentPadding: EdgeInsets.only(top: 19.v), borderDecoration: FloatingTextFormFieldStyleHelper.custom, filled: false); } 
/// Section Widget
Widget _buildExpirationDateTextField(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 5.h), child: CustomFloatingTextField(controller: expirationDateTextFieldController, labelText: "Ngày hết hạn", labelStyle: theme.textTheme.bodyMedium!, hintText: "Ngày hết hạn"))); } 
/// Section Widget
Widget _buildAddServiceButton(BuildContext context) { return CustomElevatedButton(width: 132.h, text: "Thêm dịch vụ", rightIcon: Container(margin: EdgeInsets.only(left: 5.h), child: CustomImageView(imagePath: ImageConstant.imgAddcirclebuttonremovecrossaddbuttonspluscirclemathematicsmath, height: 16.adaptSize, width: 16.adaptSize))); } 
/// Section Widget
Widget _buildAddPassengerButton(BuildContext context) { return CustomElevatedButton(width: 161.h, text: "Thêm hành khách", rightIcon: Container(margin: EdgeInsets.only(left: 5.h), child: CustomImageView(imagePath: ImageConstant.imgAddCircleBut, height: 14.adaptSize, width: 14.adaptSize))); } 
/// Section Widget
Widget _buildInfo(BuildContext context) { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildQuickEntryButton(context), SizedBox(height: 16.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Hành khách", style: CustomTextStyles.titleSmallBlack900), SizedBox(height: 16.v), _buildFullNameTextField(context), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildGenderTextField(context), Expanded(child: Container(margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 4.v), decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), _buildDateOfBirthTextField(context)])))]), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(margin: EdgeInsets.only(right: 5.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 7.v), decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: _buildPassportValueTextField(context)), _buildExpirationDateTextField(context)])]), SizedBox(height: 15.v), Padding(padding: EdgeInsets.symmetric(horizontal: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildAddServiceButton(context), _buildAddPassengerButton(context)]))])); } 
/// Section Widget
Widget _buildContactFullNameTextField(BuildContext context) { return CustomFloatingTextField(controller: contactFullNameTextFieldController, labelText: "Họ và Tên", labelStyle: theme.textTheme.bodyMedium!, hintText: "Họ và Tên"); } 
/// Section Widget
Widget _buildPhoneNumberTextField(BuildContext context) { return CustomFloatingTextField(width: 91.h, controller: phoneNumberTextFieldController, labelText: "Số điện thoại", labelStyle: theme.textTheme.bodyMedium!, hintText: "Số điện thoại", contentPadding: EdgeInsets.only(top: 22.v), borderDecoration: FloatingTextFormFieldStyleHelper.custom, filled: false); } 
/// Section Widget
Widget _buildEmailTextField(BuildContext context) { return CustomFloatingTextField(width: 156.h, controller: emailTextFieldController, labelText: "Email", labelStyle: theme.textTheme.bodyMedium!, hintText: "Email", textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, contentPadding: EdgeInsets.only(top: 21.v), borderDecoration: FloatingTextFormFieldStyleHelper.custom, filled: false); } 
/// Section Widget
Widget _buildContactInfo(BuildContext context) { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("Thông tin Liên hệ", style: CustomTextStyles.titleSmallBlack900), SizedBox(height: 15.v), _buildContactFullNameTextField(context), SizedBox(height: 15.v), Container(width: 320.h, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 4.v), decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), _buildPhoneNumberTextField(context)])), SizedBox(height: 15.v), Container(width: 320.h, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 4.v), decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), _buildEmailTextField(context)]))])); } 
/// Section Widget
Widget _buildTipTc(BuildContext context) { return CustomOutlinedButton(width: 85.h, text: "Tiếp tục", margin: EdgeInsets.only(left: 20.h, right: 2.h, bottom: 14.v)); } 
/// Section Widget
Widget _buildTotalPriceFooterRow(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 650.v, bottom: 29.v), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 10.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL10), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("1.961.250 đ", style: CustomTextStyles.titleMediumYellow900), SizedBox(height: 4.v), Text("Giá khứ hồi", style: theme.textTheme.bodySmall)])), Spacer(), Padding(padding: EdgeInsets.only(top: 12.v, bottom: 27.v), child: Text("Chi tiết", style: CustomTextStyles.labelLargeBlue700)), CustomImageView(imagePath: ImageConstant.imgArrowUpBlue700, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 2.h, top: 12.v, bottom: 27.v)), _buildTipTc(context)]))); } 
/// Common widget
Widget _buildFlightDetailsColumn1(BuildContext context, {required String cityName, required String time, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(cityName, style: CustomTextStyles.labelLargeBlack900_1.copyWith(color: appTheme.black900)), SizedBox(height: 2.v), Text(time, style: CustomTextStyles.labelLargeOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer))]); } 
/// Common widget
Widget _buildFlightDetailsColumn2(BuildContext context, {required String cityName, required String time, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text(cityName, style: CustomTextStyles.labelLargeBlack900_1.copyWith(color: appTheme.black900))), SizedBox(height: 2.v), Text(time, style: CustomTextStyles.labelLargeOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer))]); } 
/// Common widget
Widget _buildFlightDetailsColumn3(BuildContext context, {required String dateText, required String labelText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dateText, style: CustomTextStyles.bodySmallErrorContainer11.copyWith(color: theme.colorScheme.errorContainer)), SizedBox(height: 2.v), Text(labelText, style: CustomTextStyles.labelMediumErrorContainer.copyWith(color: theme.colorScheme.errorContainer))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
