import 'package:flutter/material.dart';import 'package:loc_s_application_booking/core/app_export.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_three.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_title_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_trailing_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/custom_app_bar.dart';import 'package:loc_s_application_booking/widgets/custom_outlined_button.dart';class TicketDetailScreen extends StatelessWidget {const TicketDetailScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.blue50, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTicketOverview(context), CustomOutlinedButton(height: 36.v, text: "Chặng bay thẳng", buttonStyle: CustomButtonStyles.outlineBlue, buttonTextStyle: CustomTextStyles.bodySmallErrorContainer), _buildTicketOverview1(context), SizedBox(height: 15.v), _buildPanel(context), SizedBox(height: 15.v), _buildPanel1(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 33.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlack900, margin: EdgeInsets.only(left: 10.h, top: 3.v, bottom: 5.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 10.h), child: Row(children: [AppbarSubtitleThree(text: "Hà Nội", margin: EdgeInsets.only(top: 1.v)), AppbarTitleImage(imagePath: ImageConstant.imgArrowTransferBlack90016x16, margin: EdgeInsets.only(left: 10.h, bottom: 1.v)), AppbarSubtitleThree(text: "Đà Nẵng", margin: EdgeInsets.only(left: 9.h))])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCamera1Photo, margin: EdgeInsets.fromLTRB(15.h, 4.v, 15.h, 6.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildTicketOverview(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.fromLTRB(15.h, 15.v, 15.h, 14.v), decoration: AppDecoration.bg, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Row(children: [Container(width: 58.h, padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.secondary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Text("Chiều đi", style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: Text("T5, 18 Thg11 ", style: CustomTextStyles.bodySmallErrorContainer))]), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(right: 22.h), child: Row(children: [_buildFrame(context, timeText: "20:15", weightText: "1g 20p", timeText1: "06:50"), Padding(padding: EdgeInsets.only(left: 12.h), child: SizedBox(height: 132.v, child: VerticalDivider(width: 1.h, thickness: 1.v, indent: 11.h, endIndent: 11.h))), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 256.h, child: Text("HAN - Cảng hàng không quốc tế Tân Sơn\nNhất - Tp. Hồ Chí Minh", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeOnPrimaryContainerSemiBold.copyWith(height: 1.54))), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(right: 15.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgWarning, height: 24.v, width: 34.h, margin: EdgeInsets.only(top: 14.v, bottom: 15.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Vietjet Air", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), Text("VJ148", style: theme.textTheme.bodySmall), SizedBox(height: 4.v), Text("Airbus A330-300", style: theme.textTheme.bodySmall)])), CustomImageView(imagePath: ImageConstant.imgSettings, height: 14.v, width: 96.h, margin: EdgeInsets.only(left: 5.h, top: 19.v, bottom: 20.v))])), SizedBox(height: 12.v), Text("DAD - Sân bay quốc tế Đàng Nẵng", style: CustomTextStyles.labelLargeOnPrimaryContainerSemiBold)])))]))])); } 
/// Section Widget
Widget _buildTicketOverview1(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 14.v), decoration: AppDecoration.light, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(width: 61.h, padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.secondary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Text("Chiều về", style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: Text("T2, 22 Thg11 ", style: CustomTextStyles.bodySmallErrorContainer))]), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(right: 22.h), child: Row(children: [Padding(padding: EdgeInsets.only(bottom: 3.v), child: _buildFrame(context, timeText: "20:15", weightText: "1g 20p", timeText1: "06:50")), Padding(padding: EdgeInsets.only(left: 12.h), child: SizedBox(height: 133.v, child: VerticalDivider(width: 1.h, thickness: 1.v, indent: 10.h, endIndent: 13.h))), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("DAD - Sân bay quốc tế Đàng Nẵng", style: CustomTextStyles.labelLargeOnPrimaryContainerSemiBold), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 39.h), child: Text("Vietnam Airlines", style: theme.textTheme.bodySmall)), Container(width: 240.h, margin: EdgeInsets.only(right: 15.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgWarning, height: 24.v, width: 34.h), Padding(padding: EdgeInsets.only(left: 5.h, top: 4.v, bottom: 4.v), child: Text("VN214", style: theme.textTheme.bodySmall)), Spacer(), CustomImageView(imagePath: ImageConstant.imgSettings, height: 14.v, width: 96.h, margin: EdgeInsets.symmetric(vertical: 5.v))])), Padding(padding: EdgeInsets.only(left: 39.h), child: Text("Airbus A330-300", style: theme.textTheme.bodySmall)), SizedBox(height: 11.v), SizedBox(width: 256.h, child: Text("HAN - Cảng hàng không quốc tế Tân Sơn\nNhất - Tp. Hồ Chí Minh", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeOnPrimaryContainerSemiBold.copyWith(height: 1.54)))])))]))])); } 
/// Section Widget
Widget _buildPanel(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 12.h), padding: EdgeInsets.all(14.h), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 9.v, bottom: 8.v), child: Text("1.961.250 đ", style: CustomTextStyles.titleMediumYellow900)), Padding(padding: EdgeInsets.only(left: 5.h, top: 13.v, bottom: 11.v), child: Text("/ người", style: theme.textTheme.bodySmall)), Spacer(), CustomOutlinedButton(width: 66.h, text: "Chọn")])), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgBackpackBagB, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("Đã bao gồm hành lý xách tay", style: CustomTextStyles.bodySmallErrorContainer))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 1.h, right: 26.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBaggageCheck, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 21.v)), Expanded(child: Container(width: 271.h, margin: EdgeInsets.only(left: 10.h), child: Text("Không có hành lý ký gửi miễn cước (chuyến bay\nchiêu đi)", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallErrorContainer.copyWith(height: 1.50))))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgWarningOctagon, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Không thể đổi hay hủy vé", style: CustomTextStyles.bodySmallErrorContainer))]))])); } 
/// Section Widget
Widget _buildPanel1(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 12.h), padding: EdgeInsets.all(14.h), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Thông tin hành lý & chính sách vé", style: theme.textTheme.bodyMedium), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 16.adaptSize, width: 16.adaptSize)])); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String timeText, required String weightText, required String timeText1, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(timeText, style: CustomTextStyles.titleSmallOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer)), SizedBox(height: 43.v), Text(weightText, style: CustomTextStyles.bodySmall10.copyWith(color: appTheme.gray600)), SizedBox(height: 40.v), Text(timeText1, style: CustomTextStyles.titleSmallOnPrimaryContainer.copyWith(color: theme.colorScheme.onPrimaryContainer))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
