import 'package:flutter/material.dart';import 'package:loc_s_application_booking/core/app_export.dart';import 'package:loc_s_application_booking/presentation/ticket_more_page/ticket_more_page.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_five.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_four.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_six.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_title_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_trailing_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/custom_app_bar.dart';class TicketMoreTabContainerScreen extends StatefulWidget {const TicketMoreTabContainerScreen({Key? key}) : super(key: key);

@override TicketMoreTabContainerScreenState createState() =>  TicketMoreTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class TicketMoreTabContainerScreenState extends State<TicketMoreTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 8, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: SizedBox(height: 770.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(decoration: AppDecoration.fillBlue, child: Container(height: 78.v, width: double.maxFinite, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), borderRadius: BorderRadius.vertical(bottom: Radius.circular(30.h)))))), Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.light, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildPlaneWays(context), _buildTabview(context), SizedBox(height: 764.v, child: TabBarView(controller: tabviewController, children: [TicketMorePage(), TicketMorePage(), TicketMorePage(), TicketMorePage(), TicketMorePage(), TicketMorePage(), TicketMorePage(), TicketMorePage()]))])))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 38.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftBlack900, margin: EdgeInsets.only(left: 10.h, top: 4.v, bottom: 5.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 10.h), child: Column(children: [Row(children: [AppbarSubtitleFive(text: "Chiều đi:", margin: EdgeInsets.only(bottom: 1.v)), AppbarSubtitleFive(text: "Hà Nội", margin: EdgeInsets.only(left: 10.h, top: 1.v)), AppbarTitleImage(imagePath: ImageConstant.imgArrowTransferBlack900, margin: EdgeInsets.only(left: 11.h))]), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(right: 43.h), child: Row(children: [AppbarSubtitleSix(text: "18 Tháng 11", margin: EdgeInsets.only(top: 1.v)), AppbarTitleImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 6.h))]))])), actions: [AppbarSubtitleFour(text: "Đà Nẵng", margin: EdgeInsets.only(left: 9.h, right: 6.h, bottom: 11.v)), AppbarTrailingImage(imagePath: ImageConstant.imgCamera1Photo, margin: EdgeInsets.only(left: 109.h, top: 4.v, right: 21.h))]); } 
/// Section Widget
Widget _buildPlaneWays(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 8.v), decoration: AppDecoration.primary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL10), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgTakeOffTraveOnprimary, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Chọn chuyến bay chiều đi", style: theme.textTheme.labelLarge))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return SizedBox(height: 50.v, width: 372.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, tabs: [Tab(child: Text("T4, 17 Thg11 ")), Tab(child: Text("4.720.000 đ")), Tab(child: Text("T5, 18 Thg11 ")), Tab(child: Text("4.254.500 đ")), Tab(child: Text("T5, 18 Thg11 ")), Tab(child: Text("4.854.500 đ")), Tab(child: Text("T5, 18 Thg11 ")), Tab(child: Text("4.354.500 đ"))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
