import 'package:flutter/material.dart';import 'package:loc_s_application_booking/core/app_export.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_one.dart';import 'package:loc_s_application_booking/widgets/app_bar/custom_app_bar.dart';import 'package:loc_s_application_booking/widgets/custom_outlined_button.dart';import 'package:loc_s_application_booking/widgets/custom_switch.dart';
// ignore_for_file: must_be_immutable
class ManageTicketScreen extends StatelessWidget {ManageTicketScreen({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

bool isSelectedSwitch1 = false;

bool isSelectedSwitch2 = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Container(height: 770.v, width: double.maxFinite, decoration: AppDecoration.fillBlue, child: Stack(alignment: Alignment.topCenter, children: [_buildAppBar(context), Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(left: 12.h, top: 43.v, right: 12.h), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), decoration: AppDecoration.light.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildInputRow(context), SizedBox(height: 5.v), _buildInputStack(context), _buildInputRow1(context), _buildInputRow2(context), SizedBox(height: 15.v), _buildInput(context), SizedBox(height: 15.v), _buildInputRow3(context), SizedBox(height: 15.v), CustomOutlinedButton(text: "Xem kết quả")])))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 10.h, top: 5.v, bottom: 48.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleOne(text: "Quản lý đặt chỗ", margin: EdgeInsets.only(left: 10.h, top: 8.v, bottom: 49.v)), styleType: Style.bgGradientnamelightblue500nameprimary); } 
/// Section Widget
Widget _buildInputRow(BuildContext context) { return Container(decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [Container(height: 52.v, width: 42.h, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 15.v), decoration: AppDecoration.secondary, child: CustomImageView(imagePath: ImageConstant.imgBlankCalendar, height: 22.adaptSize, width: 22.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 15.h, top: 7.v, bottom: 7.v), child: _buildFrameColumn(context, bookingDate: "Từ ngày", bookingTime: "T5, 18 Tháng 11")), Spacer(), Padding(padding: EdgeInsets.only(top: 7.v, right: 18.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Đến ngày", style: theme.textTheme.bodySmall), SizedBox(height: 5.v), Text("T2, 22 Tháng 11", style: theme.textTheme.bodyMedium)]))])); } 
/// Section Widget
Widget _buildInputStack(BuildContext context) { return SizedBox(height: 54.v, width: 320.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.fromLTRB(39.h, 15.v, 39.h, 14.v), decoration: AppDecoration.bg, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.symmetric(vertical: 4.v), child: Text("Giữ đặt chỗ", style: theme.textTheme.bodySmall)), CustomSwitch(margin: EdgeInsets.only(left: 8.h), value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})]))), Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Text("Đã xuất vé", style: theme.textTheme.bodySmall)), CustomSwitch(margin: EdgeInsets.only(left: 8.h), value: isSelectedSwitch1, onChange: (value) {isSelectedSwitch1 = value;})]))])); } 
/// Section Widget
Widget _buildInputRow1(BuildContext context) { return Container(padding: EdgeInsets.only(top: 15.v, bottom: 14.v), decoration: AppDecoration.bg, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Text("Ẩn PNR hết hạn giữ chỗ", style: theme.textTheme.bodySmall)), CustomSwitch(margin: EdgeInsets.only(left: 8.h), value: isSelectedSwitch2, onChange: (value) {isSelectedSwitch2 = value;})])); } 
/// Section Widget
Widget _buildInputRow2(BuildContext context) { return Container(padding: EdgeInsets.only(top: 17.v, bottom: 16.v), decoration: AppDecoration.bg, child: Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Hãng hàng không", style: theme.textTheme.bodySmall)), Padding(padding: EdgeInsets.only(left: 11.h), child: _buildPlaneCodeRow(context, vN: "VN")), Container(width: 40.h, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 2.v), decoration: AppDecoration.fillRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("VJ", style: theme.textTheme.labelLarge), CustomImageView(imagePath: ImageConstant.imgDelete1Remov, height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 5.h, top: 3.v, bottom: 3.v))])), Container(width: 45.h, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 2.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("QH", style: theme.textTheme.labelLarge), CustomImageView(imagePath: ImageConstant.imgDelete1Remov, height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 3.v, bottom: 3.v))])), Padding(padding: EdgeInsets.only(left: 8.h), child: _buildPlaneCodeRow(context, vN: "VU"))])); } 
/// Section Widget
Widget _buildInput(BuildContext context) { return Container(decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [Container(height: 52.v, width: 42.h, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 15.v), decoration: AppDecoration.secondary, child: CustomImageView(imagePath: ImageConstant.imgBlankCalendar, height: 22.adaptSize, width: 22.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 15.h, top: 7.v, bottom: 7.v), child: _buildFrameColumn(context, bookingDate: "Ngày đặt chỗ", bookingTime: "T5, 18 Tháng 11"))])); } 
/// Section Widget
Widget _buildInputRow3(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 7.v), decoration: AppDecoration.border.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgWarning, height: 24.v, width: 34.h, margin: EdgeInsets.symmetric(vertical: 6.v)), Padding(padding: EdgeInsets.only(left: 15.h, bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Mã đặt chỗ", style: theme.textTheme.bodySmall), SizedBox(height: 4.v), Text("123 456 789", style: theme.textTheme.bodyMedium)]))])); } 
/// Common widget
Widget _buildPlaneCodeRow(BuildContext context, {required String vN, }) { return Container(width: 44.h, padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 2.v), decoration: AppDecoration.fillBlueA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder3), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(vN, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.onPrimary.withOpacity(1))), CustomImageView(imagePath: ImageConstant.imgDelete1Remov, height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 5.h, top: 3.v, bottom: 3.v))])); } 
/// Common widget
Widget _buildFrameColumn(BuildContext context, {required String bookingDate, required String bookingTime, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(bookingDate, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.gray600)), SizedBox(height: 5.v), Text(bookingTime, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.black900))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
