import 'package:flutter/material.dart';import 'package:loc_s_application_booking/core/app_export.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_subtitle_one.dart';import 'package:loc_s_application_booking/widgets/app_bar/appbar_trailing_image.dart';import 'package:loc_s_application_booking/widgets/app_bar/custom_app_bar.dart';class CustomersScreen extends StatelessWidget {const CustomersScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 17.v), child: SizedBox(height: 729.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 54.h), decoration: AppDecoration.fillBlue, child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Thêm mới môt khách hàng thân thiết", style: theme.textTheme.titleSmall), CustomImageView(imagePath: ImageConstant.imgAddcirclebuttonremovecrossaddbuttonspluscirclemathematicsmath, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 5.h))])))), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildHeader(context), _buildCustomerItem(context, vNguyNH: "Vũ Nguyên Hồ", mr: "Mr", zipcode: "1983"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn A", mr: "Mrs", zipcode: "1985"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn B", mr: "Mr", zipcode: "2005"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn C", mr: "Miss", zipcode: "1988"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn D", mr: "Mr", zipcode: "1999"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn E", mr: "Mr", zipcode: "1993"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn F", mr: "Mr", zipcode: "1993"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn G", mr: "Mr", zipcode: "2000"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn H", mr: "Mr", zipcode: "2010"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn K", mr: "Mr", zipcode: "1983"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn M", mr: "Miss", zipcode: "2004"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn O", mr: "MrS", zipcode: "2008"), _buildCustomerItem(context, vNguyNH: "Nguyên Văn X", mr: "Mr", zipcode: "2002")]))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 43.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 10.h, top: 5.v, bottom: 13.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleOne(text: "Khách hàng thân thiết", margin: EdgeInsets.only(left: 10.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgMagnifyingglassglasssearchmagnifying, margin: EdgeInsets.fromLTRB(15.h, 6.v, 15.h, 14.v))], styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildHeader(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 14.v), decoration: AppDecoration.light, child: Row(children: [Text("Họ và Tên", style: theme.textTheme.bodySmall), Spacer(), Text("Dxưng", style: theme.textTheme.bodySmall), Padding(padding: EdgeInsets.only(left: 23.h, right: 67.h), child: Text("Năm sinh", style: theme.textTheme.bodySmall))])); } 
/// Common widget
Widget _buildCustomerItem(BuildContext context, {required String vNguyNH, required String mr, required String zipcode, }) { return Container(width: double.maxFinite, padding: EdgeInsets.fromLTRB(13.h, 14.v, 13.h, 15.v), decoration: AppDecoration.outlineBlue501, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(vNguyNH, style: CustomTextStyles.bodyMedium13.copyWith(color: appTheme.black900))), Spacer(flex: 48), Text(mr, style: CustomTextStyles.bodyMedium13.copyWith(color: appTheme.black900)), Spacer(flex: 22), Text(zipcode, style: CustomTextStyles.bodyMedium13.copyWith(color: appTheme.black900)), Spacer(flex: 28), CustomImageView(imagePath: ImageConstant.imgMenu, height: 16.v, width: 47.h)])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
